feat: add stream docs
InjectiveLabs/docs pull request #129
Opened 2023-08-07 15:55 UTC by mmeloni

This PR add docs related to new chain stream api

2023-08-07 17:12 UTC, aarmoa requested changes

2023-08-08 08:17 UTC, mmeloni commented on source/includes/_streamrpc.md
> +	cc, err := grpc.Dial("staging.stream.injective.network:443", grpc.WithTransportCredentials(creds))
This is the idiomatic go gRPC way to connect to a grpc server. In others example there is the need to use more sofisticated connection solutions in order to interact with the chain. Streamer is a simple grpc server that does not requires to use such complexity. For golang developers this is very easy to read.

2023-08-08 13:40 UTC, mmeloni commented on source/includes/_streamrpc.md
> +	cc, err := grpc.Dial("staging.stream.injective.network:443", grpc.WithTransportCredentials(creds))
But I got your point. When we will deploy prod stream dns I will change this part, ty

2023-08-09 19:43 UTC, aarmoa approved these changes
The changes look good to me since we are going to update the example when all other environment URLs are available

2023-11-02 18:22 UTC, aarmoa commented
Closing this PR because its changes have been included in https://github.com/InjectiveLabs/docs/pull/139

2023-11-02 18:22 UTC, closed without merging